language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - npm -g install node-gyp
  - sudo apt-get -qq update
  # Needed for device-bluetooth-proximity.
  - sudo apt-get install -y bluetooth bluez libbluetooth-dev libudev-dev
install:
  - npm install
script:
  - npm run test
