language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  # Needed for device-bluetooth-proximity.
  - sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
before_script:
  - npm install
script:
  - npm run test
